[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "/login"
  to = "https://ill-red-giraffe-tux.cyclic.cloud/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  base = "simulador-examen-paa-app"
  publish = "build"  # Asumiendo que tu directorio de construcción es "build"

